
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { Coins, HandCoins, Landmark } from "lucide-react";

export function TokenEconomyPanel() {
  return (
    <section>
      <div className="text-center mb-8 md:mb-12">
        <h2 className="font-headline text-3xl md:text-4xl font-bold text-foreground">Dynamic Token Economy</h2>
        <p className="mt-2 text-md md:text-lg text-muted-foreground">The financial heartbeat of the DeNeo ecosystem.</p>
      </div>
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8 items-stretch">
        <Card className="lg:col-span-2 bg-card/50 border-border/50 shadow-lg">
          <CardHeader>
            <CardTitle>Live Token Circulation</CardTitle>
            <CardDescription>Metrics on the total supply and distribution of ETH tokens.</CardDescription>
          </CardHeader>
          <CardContent className="space-y-6 pt-4">
            <div>
              <div className="flex flex-col sm:flex-row justify-between mb-1">
                <span className="text-sm font-medium text-muted-foreground flex items-center gap-2"><Coins className="text-accent" /> Total Supply</span>
                <span className="text-sm font-bold">1,000,000,000 ETH</span>
              </div>
              <Progress value={100} className="h-2" />
            </div>
            <div>
              <div className="flex flex-col sm:flex-row justify-between mb-1">
                 <span className="text-sm font-medium text-muted-foreground flex items-center gap-2"><HandCoins className="text-accent" /> Distributed Rewards</span>
                <span className="text-sm font-bold">450,000,000 ETH</span>
              </div>
              <Progress value={45} className="h-2" />
            </div>
            <div>
              <div className="flex flex-col sm:flex-row justify-between mb-1">
                 <span className="text-sm font-medium text-muted-foreground flex items-center gap-2"><Landmark className="text-accent" /> Ecosystem Treasury</span>
                <span className="text-sm font-bold">550,000,000 ETH</span>
              </div>
              <Progress value={55} className="h-2" />
            </div>
          </CardContent>
        </Card>
        <Card className="bg-card/50 border-border/50 shadow-lg flex flex-col justify-center text-center sm:text-left">
          <CardHeader>
            <CardTitle>Value of Impact</CardTitle>
            <CardDescription>Total value generated by positive ecosystem activities.</CardDescription>
          </CardHeader>
          <CardContent>
            <p className="text-4xl md:text-5xl font-bold text-accent drop-shadow-[0_0_10px_hsl(var(--accent)/0.5)]">
              $1,234,567
            </p>
            <p className="text-muted-foreground mt-2">and growing every second</p>
          </CardContent>
        </Card>
      </div>
    </section>
  );
}
